### PR TITLE
Adds Wagtail 2.0 support.

### LINKED ISSUE #26: Add Wagtail 2.0 compatibility
Given the small size of this module, it can stay compatible with Wagtail 1.x as well as 2.x using `try…except ImportError`.

Apart from the modules rename, I don’t think anything will block Wagtail 2.0 compatibility.

### PR DESCRIPTION
**Pull request by BertrandBordage**
Fixes #26.

### CODE REVIEW

**Comment by stuaxo** [comment]
:+1:

**Comment by stuaxo** [comment]
Hi @robmoorman any chance of this one being merged ?

**Comment by robmoorman** [comment]
Thanks @BertrandBordage !

**Comment by rjusher** [comment]
Hi @robmoorman is there any chance of doing a version bump to distribute this fix to pypi.
Is there an issue that is blocking the new version?

**Comment by robmoorman** [comment]
Hi @rjusher , for sure! Give me a moment; will push the new version today! Thanks for the notice.

**Comment by rjusher** [comment]
Thanks @robmoorman will check it soon.

**Pull request merged**
