### PR TITLE
 Add views for rendering a static API 

### PR DESCRIPTION
**Pull request by kaedroho**
This implements three new views for rendering pages to static JSON files
using Wagtail's API module:

- ``PagesAPIDetailView`` renders detail pages at ``/api/pages/detail/{id}.json``
- ``PagesAPIListingView`` renders a full page listing at ``/api/pages/{page_num}.json``. Each page contains 20 results.
- ``TypedPagesAPIListingView`` renders a separate listing for each page type at ``/api/pages/{app_label}.{model_name}/{page_num}.json``. Unlike the standard listing view, this also includes all specific fields on that page type.

All rendering is done through Wagtail's v2 API module so any configuration the site has for that will be used by this static renderer.

### CODE REVIEW

**Comment by robmoorman** [comment]
Great work @kaedroho ! I'll look at this during the weekend, keep you posted!

**Comment by tomdyson** [comment]
Hi @robmoorman have you had a chance to look at this? Is there anything we can help with?

**Comment by tomdyson** [comment]
@kaedroho can you please update the Configuration and Usage sections of the README to demonstrate how a developer would use the API view?

**Comment by robmoorman** [comment]
He @tomdyson just need to run some extra testing on existing projects, code looks fine (some flake8 minor things though). Should be ready to merge very soon now.

**Comment by robmoorman** [comment]
@kaedroho could you provide some tests as well?

**Comment by robmoorman** [comment]
Thanks @kaedroho and @tomdyson !

**Pull request merged**
